### ISSUE TITLE
gc询问

### ISSUE THREAD

**Issue by skywind3000** [esrrhs/fakescript#1]
vm的关键在gc呀。小代码测试不出gc问题，业务复杂点gc就关键了，请问贵脚本gc是何方法？

**Comment by esrrhs** [comment]
无gc

**Comment by asbai** [comment]
是使用引用计数之类的方式来跟踪和回收堆对象么？循环引用如何解决？

**Comment by esrrhs** [comment]
并无gc，无全局变量，接口都是函数，用到的临时map array之类的对象在脚本执行完就会全部清除

**Comment by esrrhs** [comment]
如果只是C++一般调用下函数做下数学运算条件判断的话，不用map array之类的数据结构，那么完全不用考虑内存回收的性能影响，脚本的变量都是在栈上的
