### ISSUE TITLE
请问“部分支持 JIT”具体支持哪些部分呢？

### ISSUE THREAD

**Issue by asbai** [esrrhs/fakescript#4]
如题，另外开启部分 JIT 后性能大概能提升多少呢？

多谢 :-)

**Comment by esrrhs** [comment]
除了一个for var i = 1 -> 10, 1 then xxx end的特殊写法，还有协程部分，其他都支持，但是缺乏错误处理，出了问题就会崩溃而且没堆栈所以不建议使用，还是使用解释器安全点
