### ISSUE TITLE
缺乏语法说明，我变量定义都出错

### ISSUE THREAD

**Issue by kipade** [esrrhs/fakescript#8]
我写一个递归函数：
func fibR(n)
    if (n<2) then
        return n
    end
    return fibR(n-2)+fibR(n-1)
end
在return fibR(n-2)+fibR(n-1)报错了，无奈，我定义两个变量
1: arg1 := n-1
    arg2 := n-2
2: var arg1 = n-1, arg2 = n-2
3: var arg1,arg2
    arg1 = n-1
    arg2 = n-2
横竖都不对

**Comment by esrrhs** [comment]
是个bug，这么写是ok的
```
func main()
	
	print("fibR:", fibR(10))
	
	return 0
	
end

func fibR(n)
    if (n < 2) then
        return n
    end
    return fibR(n - 2) + fibR(n - 1)
end
```
n-2识别成-2了
另外这个项目年久失修了，你可以fork自己改改或者提pr

**Comment by kipade** [comment]
怎么的就不继续了呢？

**Comment by esrrhs** [comment]
太忙
