### ISSUE TITLE
性能/正确性 问题

### ISSUE THREAD

**Issue by kipade** [esrrhs/fakescript#9]
此前在网上看到系列脚本的测试脚本,拿斐波那契数列的脚来看:
Lua:
function fibR(n)
    if (n < 2) then return n end
    return (fibR(n-2) + fibR(n-1))
end

function fibI(n)
    local last = 0
    local cur = 1
    n = n - 1
    while (n > 0)
    do
        n = n - 1
        local tmp = cur
        cur = last + cur
        last = tmp
    end
    return cur
end

改用fake重写之后:
func fibR(n)
    if (n < 2) then return n end
    return (fibR(n - 2) + fibR(n - 1))
end

func fibI(n)
    var last = 0
    var cur = 1
    n = n - 1
    while (n > 0)
    then
        n = n - 1
        var tmp = cur
        cur = last + cur
        last = tmp
    end
    return cur
end

func main()
var N = 43
print("fib: " .. fibR(N) .. " = " , fibI(N))
end

流程一样,在我i9-8950HK CPU,32GB内存的64位Linux环境下,lua要跑55秒,fake半小时都不见返回

**Comment by esrrhs** [comment]
使用./build.sh release来编译
```
# time ./fakebin t.fk
fib: 433494437 = 433494437

real    2m17.128s
user    2m17.128s
sys     0m0.000s
```
用lua执行
```
# time lua t.lua
fib: 433494437 =        433494437

real    1m40.994s
user    1m40.988s
sys     0m0.004s
```

**Comment by kipade** [comment]
果然。不过，你的Lua没我快，我的fake也没你快，执行完需要2分25秒，不过，有正确结果就很好了
